//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/DK2D/Input_Manager/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player_Inputs"",
            ""id"": ""0071ead9-3f0f-41f3-936f-c30248d1dfe1"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""db57b7be-3b89-47f5-85e5-c4c122c935dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""aabc2345-bb4b-4139-afe6-a4d646af0d18"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""02129395-5537-4158-8367-bb0c11c79ff3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""9584610f-3398-49dc-aad9-84b14b7dd4d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwordAttack"",
                    ""type"": ""Button"",
                    ""id"": ""4a62404f-3fb8-48ec-a326-ca13be9d6bab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DoubleSlash"",
                    ""type"": ""Button"",
                    ""id"": ""d1aef998-ea79-4b10-9764-30c785beb38b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap(tapDelay=0.65)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwordSpin"",
                    ""type"": ""Button"",
                    ""id"": ""0f394af8-4fe3-4bb0-ae64-dae8ae25e8d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap(tapDelay=0.55,tapCount=3)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GroundSlam"",
                    ""type"": ""Button"",
                    ""id"": ""c012ffe3-9147-4807-8fe2-0c59eb204535"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap(tapDelay=0.55,tapCount=4)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4b527aff-d1ea-43be-9ced-9a3452f8a266"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d71f877b-581c-440f-b7ea-959967c5f912"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard Movement"",
                    ""id"": ""d7d90547-4017-4a4a-935d-5fd89c3436f6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""da890c61-7564-4d74-aed8-0fc6cfee26d0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a6b20200-569e-4490-8873-c7f0dcd0c0ec"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a64f6841-e434-4d23-802a-44bf86de4818"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""96f53457-ff0b-4a50-9fa1-1b6bfc6337a8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9b070a49-8f17-4556-b009-e00e9e8a6931"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8c0a731-943e-43a6-b558-594e4279239d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9feac112-2f4f-4204-a05a-7753b61147d3"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff79d2fa-949f-45a7-9178-362836b5fbe0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3874afb-cdf0-4d7a-bf9f-be1540ef7cb6"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec11ee2d-6137-45f1-8c4c-f13138f04886"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwordAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ead19de8-6fd5-461a-a15c-7377e5890fdb"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwordAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e85543f6-3bc1-433c-a929-51fffbbaba47"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoubleSlash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43084a7d-3ac0-40ed-ae58-a2f92c2c848f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoubleSlash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f462474-0af0-4e87-af82-7f9bd8a92242"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwordSpin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b03ede8f-b58c-4d8c-ba54-ec9cc55328ad"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwordSpin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28a133f6-61e5-42c2-8db3-faf5dfeba76e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GroundSlam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bc98e48-69d3-4b53-b3c6-ae16ae39de41"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GroundSlam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player_Inputs
        m_Player_Inputs = asset.FindActionMap("Player_Inputs", throwIfNotFound: true);
        m_Player_Inputs_Interact = m_Player_Inputs.FindAction("Interact", throwIfNotFound: true);
        m_Player_Inputs_Movement = m_Player_Inputs.FindAction("Movement", throwIfNotFound: true);
        m_Player_Inputs_UseItem = m_Player_Inputs.FindAction("UseItem", throwIfNotFound: true);
        m_Player_Inputs_Menu = m_Player_Inputs.FindAction("Menu", throwIfNotFound: true);
        m_Player_Inputs_SwordAttack = m_Player_Inputs.FindAction("SwordAttack", throwIfNotFound: true);
        m_Player_Inputs_DoubleSlash = m_Player_Inputs.FindAction("DoubleSlash", throwIfNotFound: true);
        m_Player_Inputs_SwordSpin = m_Player_Inputs.FindAction("SwordSpin", throwIfNotFound: true);
        m_Player_Inputs_GroundSlam = m_Player_Inputs.FindAction("GroundSlam", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_Inputs
    private readonly InputActionMap m_Player_Inputs;
    private List<IPlayer_InputsActions> m_Player_InputsActionsCallbackInterfaces = new List<IPlayer_InputsActions>();
    private readonly InputAction m_Player_Inputs_Interact;
    private readonly InputAction m_Player_Inputs_Movement;
    private readonly InputAction m_Player_Inputs_UseItem;
    private readonly InputAction m_Player_Inputs_Menu;
    private readonly InputAction m_Player_Inputs_SwordAttack;
    private readonly InputAction m_Player_Inputs_DoubleSlash;
    private readonly InputAction m_Player_Inputs_SwordSpin;
    private readonly InputAction m_Player_Inputs_GroundSlam;
    public struct Player_InputsActions
    {
        private @PlayerControls m_Wrapper;
        public Player_InputsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_Player_Inputs_Interact;
        public InputAction @Movement => m_Wrapper.m_Player_Inputs_Movement;
        public InputAction @UseItem => m_Wrapper.m_Player_Inputs_UseItem;
        public InputAction @Menu => m_Wrapper.m_Player_Inputs_Menu;
        public InputAction @SwordAttack => m_Wrapper.m_Player_Inputs_SwordAttack;
        public InputAction @DoubleSlash => m_Wrapper.m_Player_Inputs_DoubleSlash;
        public InputAction @SwordSpin => m_Wrapper.m_Player_Inputs_SwordSpin;
        public InputAction @GroundSlam => m_Wrapper.m_Player_Inputs_GroundSlam;
        public InputActionMap Get() { return m_Wrapper.m_Player_Inputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_InputsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayer_InputsActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_InputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_InputsActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @UseItem.started += instance.OnUseItem;
            @UseItem.performed += instance.OnUseItem;
            @UseItem.canceled += instance.OnUseItem;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @SwordAttack.started += instance.OnSwordAttack;
            @SwordAttack.performed += instance.OnSwordAttack;
            @SwordAttack.canceled += instance.OnSwordAttack;
            @DoubleSlash.started += instance.OnDoubleSlash;
            @DoubleSlash.performed += instance.OnDoubleSlash;
            @DoubleSlash.canceled += instance.OnDoubleSlash;
            @SwordSpin.started += instance.OnSwordSpin;
            @SwordSpin.performed += instance.OnSwordSpin;
            @SwordSpin.canceled += instance.OnSwordSpin;
            @GroundSlam.started += instance.OnGroundSlam;
            @GroundSlam.performed += instance.OnGroundSlam;
            @GroundSlam.canceled += instance.OnGroundSlam;
        }

        private void UnregisterCallbacks(IPlayer_InputsActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @UseItem.started -= instance.OnUseItem;
            @UseItem.performed -= instance.OnUseItem;
            @UseItem.canceled -= instance.OnUseItem;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @SwordAttack.started -= instance.OnSwordAttack;
            @SwordAttack.performed -= instance.OnSwordAttack;
            @SwordAttack.canceled -= instance.OnSwordAttack;
            @DoubleSlash.started -= instance.OnDoubleSlash;
            @DoubleSlash.performed -= instance.OnDoubleSlash;
            @DoubleSlash.canceled -= instance.OnDoubleSlash;
            @SwordSpin.started -= instance.OnSwordSpin;
            @SwordSpin.performed -= instance.OnSwordSpin;
            @SwordSpin.canceled -= instance.OnSwordSpin;
            @GroundSlam.started -= instance.OnGroundSlam;
            @GroundSlam.performed -= instance.OnGroundSlam;
            @GroundSlam.canceled -= instance.OnGroundSlam;
        }

        public void RemoveCallbacks(IPlayer_InputsActions instance)
        {
            if (m_Wrapper.m_Player_InputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer_InputsActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_InputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_InputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player_InputsActions @Player_Inputs => new Player_InputsActions(this);
    public interface IPlayer_InputsActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnSwordAttack(InputAction.CallbackContext context);
        void OnDoubleSlash(InputAction.CallbackContext context);
        void OnSwordSpin(InputAction.CallbackContext context);
        void OnGroundSlam(InputAction.CallbackContext context);
    }
}
