//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/DK2D/Input_Manager/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player_Inputs"",
            ""id"": ""0071ead9-3f0f-41f3-936f-c30248d1dfe1"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""db57b7be-3b89-47f5-85e5-c4c122c935dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4b527aff-d1ea-43be-9ced-9a3452f8a266"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player_Inputs
        m_Player_Inputs = asset.FindActionMap("Player_Inputs", throwIfNotFound: true);
        m_Player_Inputs_Interact = m_Player_Inputs.FindAction("Interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_Inputs
    private readonly InputActionMap m_Player_Inputs;
    private List<IPlayer_InputsActions> m_Player_InputsActionsCallbackInterfaces = new List<IPlayer_InputsActions>();
    private readonly InputAction m_Player_Inputs_Interact;
    public struct Player_InputsActions
    {
        private @PlayerControls m_Wrapper;
        public Player_InputsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_Player_Inputs_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Player_Inputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_InputsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayer_InputsActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_InputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_InputsActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IPlayer_InputsActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IPlayer_InputsActions instance)
        {
            if (m_Wrapper.m_Player_InputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer_InputsActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_InputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_InputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player_InputsActions @Player_Inputs => new Player_InputsActions(this);
    public interface IPlayer_InputsActions
    {
        void OnInteract(InputAction.CallbackContext context);
    }
}
